// ---------------------------------------------------------------------------
//  File    : TokenAccountActions.cs
//  Project : Okta API Token CPM Plugin (OktaApiTokenPlugin.dll) - Option A on the .NET SDK
//  Purpose : Actions for the API token account itself (platform setting OktaObjectType=ApiToken)
//  Author  : Anilkumar Dadi | Anilkumar.Dadi@cyderes.com | Cyderes
//  Version : 1.0
//  Date    : 15-Sep-2026
// ---------------------------------------------------------------------------
using System;
using CyberArk.Extensions.Plugins.Models;
using CyberArk.Extensions.Utilties.Logger;

namespace CyberArk.Extensions.Plugin.OktaOAuth
{
    /// <summary>
    /// The token account: Address = the Okta org, Username = the service administrator that owns the token,
    /// Password = the Okta API token. Okta has no API to create or rotate API tokens, so the CPM actions are:
    ///
    ///   Verify / Logon   GET /api/v1/users/me with the vaulted token - proves it is valid and, as a side effect,
    ///                    resets Okta's 30-day inactivity expiry (keep-alive)
    ///   Change           only through "specify next password": an administrator creates the new token in the
    ///                    Okta Admin Console and enters it in PVWA; the plugin proves the new token, checks it
    ///                    belongs to the same administrator as the current one, revokes the current token in
    ///                    Okta, and returns 0 so the CPM vaults the new value. A CPM-generated password can never
    ///                    be an Okta token, so a periodic or random Change is refused with 8451 and nothing
    ///                    changes in Okta or the Vault.
    ///   Reconcile        not possible (8452) - there is no credential Okta could use to mint a token.
    /// </summary>
    internal static class TokenAccountActions
    {
        public const string PlatformSettingName = "OktaObjectType";

        internal static bool IsTokenPlatform(BaseAction a)
        {
            return string.Equals(a.GetSetting(PlatformSettingName, "User"), "ApiToken", StringComparison.OrdinalIgnoreCase);
        }

        private sealed class Ctx { public string Org, Owner, Current, Next; public int Timeout; }

        private static Ctx Build(BaseAction a, bool needNext)
        {
            var c = new Ctx
            {
                Org = a.ParametersAPI.GetMandatoryParameter("address", a.Target.AccountProp),
                Owner = a.ParametersAPI.GetMandatoryParameter("username", a.Target.AccountProp),
                Current = a.ReadSecret(a.Target, false),
                Timeout = BaseAction.ToInt(a.GetSetting("HttpTimeoutSeconds", "30"), 30)
            };
            if (needNext) c.Next = a.ReadSecret(a.Target, true);
            Logger.WriteLine("Token account: org=" + c.Org + " owner=" + c.Owner, LogLevel.INFO);
            return c;
        }

        internal static int Logon(BaseAction a, ref PlatformOutput output)
        {
            return Verify(a, ref output);
        }

        internal static int Verify(BaseAction a, ref PlatformOutput output)
        {
            Ctx c = Build(a, false);
            if (!OktaApiClient.IsApiToken(c.Current))
                throw new OktaException(OktaRc.KEY_FORMAT_ERROR, "The vaulted value is not an Okta API token (expected 42 characters starting with 00).");
            using (var okta = new OktaApiClient(c.Org, c.Timeout, Log))
            {
                OktaUser owner = okta.WhoAmI(OktaApiClient.SswsAuthorization(c.Current));
                output.Message = "Okta API token verified - owner " + owner.Login + " (keep-alive: the 30-day inactivity expiry has been reset).";
            }
            return OktaRc.SUCCESS;
        }

        internal static int Change(BaseAction a, ref PlatformOutput output)
        {
            Ctx c = Build(a, true);
            if (!OktaApiClient.IsApiToken(c.Next))
                throw new OktaException(OktaRc.TOKEN_CHANGE_REFUSED,
                    "Okta API tokens cannot be generated by the CPM. Create the new token in the Okta Admin Console (Security > API > Tokens, signed in as the token owner) and use Change > 'specify next password' with that value.");
            if (c.Next == c.Current)
                throw new OktaException(OktaRc.TOKEN_CHANGE_REFUSED, "The new token is identical to the current one.");

            using (var okta = new OktaApiClient(c.Org, c.Timeout, Log))
            {
                // 1. the new token must work, and belong to the same administrator
                OktaUser newOwner = okta.WhoAmI(OktaApiClient.SswsAuthorization(c.Next));
                OktaUser curOwner = null;
                try { if (OktaApiClient.IsApiToken(c.Current)) curOwner = okta.WhoAmI(OktaApiClient.SswsAuthorization(c.Current)); }
                catch (OktaException ex) { Logger.WriteLine("Current token is no longer valid (" + ex.Message + ") - nothing to revoke", LogLevel.INFO); }

                if (curOwner != null && !string.Equals(curOwner.Id, newOwner.Id, StringComparison.OrdinalIgnoreCase))
                    throw new OktaException(OktaRc.TOKEN_OWNER_MISMATCH,
                        "The new token belongs to " + newOwner.Login + " but the current one belongs to " + curOwner.Login + ". Create the token while signed in as " + curOwner.Login + ".");
                if (!string.Equals(newOwner.Login, c.Owner, StringComparison.OrdinalIgnoreCase))
                    Logger.WriteLine("WARNING: the token owner (" + newOwner.Login + ") differs from the account Username (" + c.Owner + ")", LogLevel.WARNING);

                // 2. retire the previous token (best effort - the new token is already proven)
                string note = "previous token was already invalid";
                if (curOwner != null)
                {
                    try { okta.RevokeCurrentToken(OktaApiClient.SswsAuthorization(c.Current)); note = "previous token revoked"; }
                    catch (Exception ex)
                    {
                        Logger.WriteLine("WARNING: could not revoke the previous token: " + ex.Message + " - revoke it in Security > API > Tokens", LogLevel.WARNING);
                        note = "previous token NOT revoked - revoke it manually in Okta";
                    }
                }
                output.Message = "Okta API token replaced for " + newOwner.Login + " (" + note + ").";
            }
            return OktaRc.SUCCESS;   // the CPM now stores the new token
        }

        internal static int Prereconcile(BaseAction a, ref PlatformOutput output)
        {
            throw new OktaException(OktaRc.TOKEN_RECONCILE_NA, "Reconcile is not possible for an Okta API token: Okta cannot create tokens by API. Create a new token in the Admin Console and use Change > 'specify next password'.");
        }

        internal static int Reconcile(BaseAction a, ref PlatformOutput output)
        {
            return Prereconcile(a, ref output);
        }

        private static void Log(string s) { Logger.WriteLine(s, LogLevel.INFO); }
    }
}
